#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
#
# This option supports custom types so lessons can be branded
# and themed with your own logo and alt-text (see `carpentry_description`)
# See https://carpentries.github.io/sandpaper-docs/editing.html#adding-a-custom-logo
carpentry: 'incubator'

# Alt-text description of the lesson.
carpentry_description: 'An introduction lesson to PRONOM and file format identification'

# Organisation.
organization_name: "Preservica, BYU, TNA, FFDev.info"

# Overall title for pages.
title: 'What’s in the box: an exploration of container-based file format identification'

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: ~ # FIXME

# Comma-separated list of keywords for the lesson
keywords: 'PRONOM, DROID, Siegfried, FIDO, Format Identification, Digipres, Lesson'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'beta' # FIXME

# License of the lesson
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/ffdev-info/searching-for-a-signature' # FIXME

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'team@carpentries.org' # FIXME

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes:
- 001-introduction.md
- 002-bridging-the-workshops.md
- 003-a-ff-structures.md
- 003-b-ff-structures.md
- 004-container-formats.md
- 005-ms-word.md
- 006-binary-signatures-recap.md
- 007-binary-identification-pronom.md
- 008-xml-primer.md
- 009-container-identfication.md
- 010-creating-a-container-xml.md
- 011-finding-sample-formats.md
- 012-plugging-it-in.md
- 013-doing-it-for-yourself.md
- 014-teaching-us-how.md
- 015-questions-and-answers.md
- 016-testing-signatures.md
- 017-wrapping-up.md

# Information for Learners. The pages here will land in the introductory
# sections.
learners:

# Information for Instructors. The pages here will be included in the
# instructor notes section.
instructors:

# Learner Profiles
profiles:
- learner-profiles.md
- instructor-profiles.md

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live

url: https://ffdev-info.github.io/searching-for-a-signature/
